name: Pull Request Checker
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  branch_check:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - uses: actions/github-script@v4.0.2
        if: ${{ github.event.pull_request.base.ref != 'develop' }} # switch branch to develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              base: 'develop'
            })
  reviewer_assign:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2 # assign reviewer
        with:
          configuration-path: ".github/pr_review.yml"
  title_check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            perf
            fix
            refactor
            deps
            build
            chore
            docs
            style
          requireScope: false

