name: Merge Pull Request
on:
  pull_request_review:
    types: [ submitted ]
  check_suite:
    types: [ completed ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' }}
    steps:
      - uses: taichi/approved-event-action@v1.2.1
        id: approved
        with:
          approvals: '2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v4.0.2
        if: ${{ steps.approved.outputs.approved == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commits } = await github.pulls.listCommits({
              ...context.repo,
              pull_number: context.payload.pull_request.number
            });

            github.pulls.merge({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash',
              commit_title: `${context.payload.pull_request.title} (#${context.payload.pull_request.number})`,
              commit_message: commits.map(commit => '* ' + commit.commit.message.split('\n')[0]).join('\n')
            });
