name: Release
on:
  workflow_dispatch:

env:
  RELEASE: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSPHRASE: ${{ secrets.OSSRH_PASSPHRASE }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: actions/cache@v2.1.5
        name: Gradle Cache JDK11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: JDK11-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: JDK11-gradle-
      - uses: actions/setup-java@v2
        name: Setup JDK11
        with:
          java-version: 11
          distribution: adopt
          gpg-private-key: ${{ secrets.GPG_KEY }}
      - uses: actions/setup-node@v2.1.5
        name: Setup NodeJS
      - uses: cycjimmy/semantic-release-action@v2.5.4
        name: Release
        id: semantic
        with:
          branch: main
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-conventionalcommits
